### ISSUE TITLE
BookCard Code Review

### ISSUE THREAD

**Issue by hunjoonrhee** [BookDo7starsTS/bookdo7star_fe#16]
코드 리뷰를 하다 몇가지 눈에 띄었던 점들이 있어서 이슈 올려봅니다.

1. CardMedia 에 sx 속성에서  cursor: poiner 라고 오타가 되어있습니다.
2. `{book.title}`, `{book.author}`에 속성이 중복되는데, 하나의 스타일 상수로 묶을 수 있지 않을까 싶습니다.
```
const textStyle = {
  textOverflow: 'ellipsis',
  overflow: 'hidden',
  whiteSpace: 'nowrap',
  width: '100%',
  textAlign: 'left',
  fontWeight: 'bold',
};
```

3. 지피티의 의견을 들어보면, 아이콘 버튼에는 접근성을 위해 aria-label을 추가하는 것이 좋다고 합니다. 이 속성은 화면 리더기가 버튼의 목적을 인식하는데 도움을 준다고 해요.
```
<IconButton sx={{ padding: '5px' }} aria-label="add to favorites">
  <FavoriteBorderIcon fontSize="small" sx={{ color: pink[500] }} />
</IconButton>
<IconButton sx={{ padding: '5px' }} aria-label="add to cart">
  <ShoppingCartIcon fontSize="small" />
</IconButton>
```

이정도를 수정해보면 어떨까 합니다!

**Comment by MayHyeyeonKim** [comment]
> 코드 리뷰를 하다 몇가지 눈에 띄었던 점들이 있어서 이슈 올려봅니다.
> 
> 1. CardMedia 에 sx 속성에서  cursor: poiner 라고 오타가 되어있습니다.
> 2. `{book.title}`, `{book.author}`에 속성이 중복되는데, 하나의 스타일 상수로 묶을 수 있지 않을까 싶습니다.
> 
> ```
> const textStyle = {
>   textOverflow: 'ellipsis',
>   overflow: 'hidden',
>   whiteSpace: 'nowrap',
>   width: '100%',
>   textAlign: 'left',
>   fontWeight: 'bold',
> };
> ```
> 
> 3. 지피티의 의견을 들어보면, 아이콘 버튼에는 접근성을 위해 aria-label을 추가하는 것이 좋다고 합니다. 이 속성은 화면 리더기가 버튼의 목적을 인식하는데 도움을 준다고 해요.
> 
> ```
> <IconButton sx={{ padding: '5px' }} aria-label="add to favorites">
>   <FavoriteBorderIcon fontSize="small" sx={{ color: pink[500] }} />
> </IconButton>
> <IconButton sx={{ padding: '5px' }} aria-label="add to cart">
>   <ShoppingCartIcon fontSize="small" />
> </IconButton>
> ```
> 
> 이정도를 수정해보면 어떨까 합니다!

Thank you for your review! 👍
